# Generated by Django 4.2 on 2023-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cpic', models.ImageField(upload_to='customer pics')),
                ('cno', models.CharField(max_length=50)),
                ('emil', models.EmailField(max_length=50)),
                ('dob', models.DateTimeField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adrs', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('fcont', models.IntegerField(max_length=50)),
                ('wadrs', models.CharField(max_length=50)),
                ('hoby', models.CharField(max_length=50)),
                ('occutn', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
            ],
        ),
    ]
