# Generated by Django 4.2 on 2023-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='dob',
            field=models.DateField(max_length=50),
        ),
    ]
