# Generated by Django 4.2 on 2023-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0002_alter_customerdb_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdb',
            name='quali',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
