# Generated by Django 4.2 on 2023-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0004_alter_customerdb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='cno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='fcont',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
