# Generated by Django 4.2 on 2023-08-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0006_feedbackdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedbackdb',
        ),
    ]
