# Generated by Django 4.2 on 2023-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userregistrationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('uemail', models.EmailField(blank=True, max_length=50, null=True)),
                ('upass', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
