# Generated by Django 4.2 on 2023-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_sendmessagedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessagedb',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendmessagedb',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
