# Generated by Django 4.2 on 2023-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_sendmessagedb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagedb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
