# Generated by Django 4.2 on 2023-08-01 17:14

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='receivemsgdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=userapp.models.sendmessagedb)),
                ('fname', models.CharField(blank=True, max_length=100, null=True, verbose_name=userapp.models.sendmessagedb)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name=userapp.models.sendmessagedb)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
