# Generated by Django 4.2 on 2023-08-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_message_delete_receivemsgdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
