# Generated by Django 4.2 on 2023-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_fn',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
