# Generated by Django 4.2 on 2023-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_remove_feedback_fn_user_id_feedback_fn_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagedb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
