# Generated by Django 4.2 on 2023-08-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_sendmessagedb_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback_fn',
        ),
    ]
