# Generated by Django 4.2 on 2023-08-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_delete_feedback_fn'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
