# Generated by Django 4.2 on 2023-08-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_receivemsgdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemsgdb',
            name='user',
        ),
        migrations.AddField(
            model_name='receivemsgdb',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgs', to='userapp.sendmessagedb'),
        ),
        migrations.AlterField(
            model_name='receivemsgdb',
            name='fname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivemsg', to='userapp.sendmessagedb'),
        ),
        migrations.AlterField(
            model_name='receivemsgdb',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.sendmessagedb'),
        ),
    ]
