# Generated by Django 4.2 on 2023-08-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_contactdb_delete_receivemsgdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='successstorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_image', models.CharField(blank=True, max_length=100, null=True)),
                ('story', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
