# Generated by Django 4.2 on 2023-08-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_successstorydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstorydb',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='successstory_photo'),
        ),
    ]
