# Generated by Django 4.2 on 2023-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_alter_successstorydb_c_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstorydb',
            name='c_image',
            field=models.ImageField(null=True, upload_to='successstory_photo'),
        ),
    ]
