# Generated by Django 4.2 on 2023-09-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_verificationdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationdb',
            old_name='name',
            new_name='reciever',
        ),
        migrations.AddField(
            model_name='verificationdb',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
